// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARmjjKNC-fGWqyJUiJFT6sqLYlCZD2IDQ',
    appId: '1:84104652853:web:fb9ff6abd915c4c4ab297c',
    messagingSenderId: '84104652853',
    projectId: 'lavamaxapp',
    authDomain: 'lavamaxapp.firebaseapp.com',
    storageBucket: 'lavamaxapp.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC79PpLoMyki_zOMAJC2A95BPb7WXAb5hs',
    appId: '1:84104652853:android:b17707dafada20bcab297c',
    messagingSenderId: '84104652853',
    projectId: 'lavamaxapp',
    storageBucket: 'lavamaxapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfj4tN5mgIV2oHUJ_mTlx5q0hcuDr9pdE',
    appId: '1:84104652853:ios:9f7fcf34e888c8acab297c',
    messagingSenderId: '84104652853',
    projectId: 'lavamaxapp',
    storageBucket: 'lavamaxapp.firebasestorage.app',
    iosBundleId: 'com.lavamax.lavamax',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARmjjKNC-fGWqyJUiJFT6sqLYlCZD2IDQ',
    appId: '1:84104652853:web:b50b86b2d74f4299ab297c',
    messagingSenderId: '84104652853',
    projectId: 'lavamaxapp',
    authDomain: 'lavamaxapp.firebaseapp.com',
    storageBucket: 'lavamaxapp.firebasestorage.app',
  );
}
